---
title: "Chicago Neighborhood-Level Street Tree Stress Analysis"
author: "Renata Poulton Kamakura"
date: "2024-08-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##Group means for segment data
library(dplyr)

##Visuals
library(ggplot2)

##dataframe manipulation
library(dplyr)

#for your diversity metrics
library(vegan)

#for beta regressions
library(betareg)
library(StepBeta)

#for stepwise poisson
library(My.stepwise)

#for VIF
library(car)

```


##Correlations between Predictors


```{r predictor covariance}
Seg_allData <- read.csv("../01Data/Chicago/ChicagoSegmentData.csv")

wts <- as.vector(Seg_allData$totNumTrees)
Seg_allData$AllConst_since11 <- Seg_allData$NumConst_since11 + Seg_allData$NumReno_since11

#to get a sense of the correlations
ChiCors <- cor(Seg_allData[,c("PercComm_z", "PercCOMM_MxTree", "PercRes_z","NumConst_since11",
                              "NumReno_since11", "AllConst_since11",  "NumBuild", "SVI",
                              "Change_PHL", "Change_PBl","Change_PWnHL",
                   "Change_MedHHI", "Avg_PRent","Avg_Rmov", "PercWhiteNonHL21",
                   "MedHouseInc21", "PercRent21","PercRMov21" )])

#######################################################################################################

###Use to translate from the labels from the grids to labels in paper

########More of an FYI for anyone reading this later
# InitialSegNames <- c("49", "157", "55", "153", "244", 
#             "275", "57", "128", "292", "281",
#             "306", "324", "16")
# PaperSegNames <- c(12, 13, 10, 11, 7,
#                    9, 6, 8, 5, 4,
#                    2, 3, 1)
# 
# Seg_allData$Segment[match(Seg_allData$Segment, InitialSegNames)] <- PaperSegNames[match(Seg_allData$Segment, InitialSegNames)]
```


##Regressions for Response Variables
```{r Main Regressions}

###########Model options without super correlated variables
f1 <- "PercResTree + AvgBA + Change_PWnHL + Change_MedHHI + Avg_Rmov"
f2 <- "PercResTree + AvgBA + SVI + Change_PWnHL + Change_MedHHI + Avg_Rmov"
f3 <- "PercResTree + AvgBA + AllConst_since11 + Change_PWnHL + Change_MedHHI + Avg_Rmov"


############################ Simpson Diversity - species
mods_m1 <- paste(rep("SimpsonsDivSpp ~", 2), c(f1, f2, f3))

f1mod.1 <- betareg(mods_m1[1], data=Seg_allData, weights=wts)
bestf1mod.1 <- StepBeta(f1mod.1)
f1sum.1 <- summary(bestf1mod.1)

f1mod.2 <- betareg(mods_m1[2], data=Seg_allData, weights=wts)
bestf1mod.2 <- StepBeta(f1mod.2)
f1sum.2 <- summary(bestf1mod.2)

f1mod.3 <- betareg(mods_m1[3], data=Seg_allData, weights=wts)
bestf1mod.3 <- StepBeta(f1mod.3)
f1sum.3 <- summary(bestf1mod.3)


AIC(bestf1mod.1, bestf1mod.2, bestf1mod.3)

##Results from AIC Run
#             df       AIC
# bestf1mod.1  6 -2593.319
# bestf1mod.2  7 -2595.150
# bestf1mod.3  6 -2593.319


##Number of Trees
#This model should be different because should not use number of residential
##trees as a predictor here (use % of area rather than % of trees)
f1.2 <- "PercRes_z  + AvgBA + Change_PWnHL + Change_MedHHI + Avg_Rmov"
f2.2 <- "PercRes_z  + AvgBA + SVI + Change_PWnHL + Change_MedHHI + Avg_Rmov"
f3.2 <- "PercRes_z  + AvgBA + AllConst_since11 + Change_PWnHL + Change_MedHHI + Avg_Rmov"

mods_m2 <- paste(rep("totNumTrees ~", 2), c(f1.2, f2.2, f3.2))

f2mod.1 <- step(glm(mods_m2[1], family="poisson", data=Seg_allData))
f2sum.1 <- summary(f2mod.1)

f2mod.2 <- step(glm(mods_m2[2], family="poisson", data=Seg_allData))
f2sum.2 <- summary(f2mod.2)

f2mod.3 <- step(glm(mods_m2[3], family="poisson", data=Seg_allData))
f2sum.3 <- summary(f2mod.3)

AIC(f2mod.1, f2mod.2, f2mod.3)

##Results from AIC Run
#         df      AIC
# f2mod.1  4 142.0212
# f2mod.2  4 138.8917
# f2mod.3  4 142.0212

###Urban Tolerance
mods_m3 <- paste(rep("PercUrbanApp ~", 2), c(f1, f2, f3))

f3mod.1 <- betareg(mods_m3[1], data=Seg_allData, weights=wts)
bestf3mod.1 <- StepBeta(f3mod.1)
f3sum.1 <- summary(bestf3mod.1)

f3mod.2 <- betareg(mods_m3[2], data=Seg_allData, weights=wts)
bestf3mod.2 <- StepBeta(f3mod.2)
f3sum.2 <- summary(bestf3mod.2)

f3mod.3 <- betareg(mods_m3[3], data=Seg_allData, weights=wts)
bestf3mod.3 <- StepBeta(f3mod.3)
f3sum.3 <- summary(bestf3mod.3)

AIC(bestf3mod.1, bestf3mod.2, bestf3mod.3)

##Results from AIC Run
#             df       AIC
# bestf3mod.1  6 -1985.569
# bestf3mod.2  7 -1985.752
# bestf3mod.3  8 -1999.153


##########################################################Tree Stress

###########################Discoloration
mods_m4 <- paste(rep("PercDisc3o4 ~", 2), c(f1, f2, f3))

f4mod.1 <- betareg(mods_m4[1], data=Seg_allData, weights=wts)
bestf4mod.1 <- StepBeta(f4mod.1)
f4sum.1 <- summary(bestf4mod.1)

f4mod.2 <- betareg(mods_m4[2], data=Seg_allData, weights=wts)
bestf4mod.2 <- StepBeta(f4mod.2)
f4sum.2 <- summary(bestf4mod.2)

f4mod.3 <- betareg(mods_m4[3], data=Seg_allData, weights=wts)
bestf4mod.3 <- StepBeta(f4mod.3)
f4sum.3 <- summary(bestf4mod.3)

AIC(bestf4mod.1, bestf4mod.2, bestf4mod.3)

##Results from AIC Run
#             df       AIC
# bestf4mod.1  7 -2845.292
# bestf4mod.2  8 -2845.253
# bestf4mod.3  7 -2854.339



###########################Dieback
mods_m5 <- paste(rep("PercDBK5 ~", 2), c(f1, f2, f3))

f5mod.1 <- betareg(mods_m5[1], data=Seg_allData, weights=wts)
bestf5mod.1 <- StepBeta(f5mod.1)
f5sum.1 <- summary(bestf5mod.1)

f5mod.2 <- betareg(mods_m5[2], data=Seg_allData, weights=wts)
bestf5mod.2 <- StepBeta(f5mod.2)
f5sum.2 <- summary(bestf5mod.2)

f5mod.3 <- betareg(mods_m5[3], data=Seg_allData, weights=wts)
bestf5mod.3 <- StepBeta(f5mod.3)
f5sum.3 <- summary(bestf5mod.3)


AIC(bestf5mod.1, bestf5mod.2, bestf5mod.3)

##Results from AIC Run
#              df       AIC
# bestf5mod.1  6 -3002.676
# bestf5mod.2  7 -3063.157
# bestf5mod.3  8 -3239.208


###########################Crown Stress
mods_m6 <- paste(rep("PercCS4o5 ~", 2), c(f1, f2, f3))

f6mod.1 <- betareg(mods_m6[1], data=Seg_allData, weights=wts)
bestf6mod.1 <- StepBeta(f6mod.1)
f6sum.1 <- summary(bestf6mod.1)

f6mod.2 <- betareg(mods_m6[2], data=Seg_allData, weights=wts)
bestf6mod.2 <- StepBeta(f6mod.2)
f6sum.2 <- summary(bestf6mod.2)

f6mod.3 <- betareg(mods_m6[3], data=Seg_allData, weights=wts)
bestf6mod.3 <- StepBeta(f6mod.3)
f6sum.3 <- summary(bestf6mod.3)


AIC(bestf6mod.1, bestf6mod.2, bestf6mod.3)

##Results from AIC Run
#              df       AIC
# bestf6mod.1  7 -2546.494
# bestf6mod.2  8 -2560.262
# bestf6mod.3  8 -2616.825


##store data from the "best" models
cnms <- c("ModelType", "DepVar", "model", "R2")
ModOverview <- as.data.frame(matrix(0, nrow=6, ncol=length(cnms)))
names(ModOverview) <- cnms

modList <- list(f1sum.3, f2sum.2, f3sum.3, f4sum.3, f5sum.3, f6sum.3)
modTyps <- c("beta", "pois", "beta", "beta", "beta", "beta")
modDep <- c("SimpDivSpp", "NumTrees", "PercUrbanApp", "PercDisc", "PercDBK", "PercCS")

for (m in 1:6){

  mod <- modList[[m]]
  modT <- modTyps[m]

  ModOverview$ModelType[m] <- modT
  ModOverview$DepVar[m] <- modDep[m]

  #store data for diff model types
  if(modT == "beta"){

    ModOverview$model[m] <- as.character(mod$call)
    ModOverview$R2[m] <- mod$pseudo.r.squared

    pm <- mod$coefficients$mean

  } else if (modT == "lin"){

    ModOverview$model[m] <- as.character(mod$call)[2]
    ModOverview$R2[m] <- mod$adj.r.squared

    pm <- mod$coefficients

  }else if (modT == "pois"){
    ModOverview$model[m] <- as.character(mod$call)[2]
    ModOverview$R2[m] <- with(mod, 1-deviance/null.deviance)

    pm <- mod$coefficients

  }

  ##printout the coefficient values

  write.csv(pm, paste("../03Outputs/Chicago/", modDep[m], ".csv", sep=""))


}

write.csv(ModOverview, "../04Outputs/Chicago/Chi_ModelOverviewResults.csv")




```

