---
title: "Chicago Data Cleaning"
output: html_document
date: "2024-08-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##Group means for segment data
library(dplyr)

##Visuals
library(ggplot2)

##dataframe manipulation
library(dplyr)

#for your diversity metrics
library(vegan)

#for VIF
library(car)

```


```{r read in tree lvl data}
#read in full version of the tree dataset
TreeLvlCombined <- read.csv("../01Data/Chicago/091223AllYearsComb.csv")

TodayDate <- Sys.Date()
date <- format(TodayDate, format="%b%d%y")

##census data
CensusTracts2010 <- read.csv("../01Data/Chicago/Chicago2010Census_bySeg_fix.csv")
CensusTracts2020 <- read.csv("../01Data/Chicago/Chicago2020Census_bySeg_fix.csv")
HispLat2011 <- read.csv("../01Data/Chicago/Chicago_HispLat_ACS2011.csv")
HispLat2021 <- read.csv("../01Data/Chicago/Chicago_HispLat_ACS2021.csv")
MedHouseInc2011 <- read.csv("../01Data/Chicago/Chicago_MedHouseInc_ACS2011_2011InflAdj.csv")
MedHouseInc2021 <- read.csv("../01Data/Chicago/Chicago_MedHouseInc_ACS2021_2021InflAdj.csv")
HousingTenure2011 <- read.csv("../01Data/Chicago/Chicago_HousingTenure_ACS2011.csv")
HousingTenure2021 <- read.csv("../01Data/Chicago/Chicago_HousingTenure_ACS2021.csv")
SVIData <- read.csv("../01Data/Chicago/CookCounty_SVI.csv")

##zoning data
ZoningData <- read.csv("../01Data/Chicago/ChicagoZoning_bySeg_fix.csv")
ZoningDescr <- read.csv("../01Data/Chicago/ChicagoZoningDescriptions.csv")

#building data
BFoot  <- read.csv("../01Data/Chicago/ChicagoBuildings_bySeg_fix.csv")
BPerm  <- read.csv("../01Data/Chicago/Chicago_BuildingPermits_wSeg_clean.csv")

#tree species information
SppSpecificData <- read.csv("../01Data/Chicago/SpeciesInformation_Chicago_Dirr.csv")


```


##Useful Functions
```{r useful funcs}
sumSquares <- function(predicted, actual){
  
  ss <- 0
  
  for(s in 1:length(predicted)){
    
    ss <- ss + (predicted[s] - actual[s])^2
    
    if( is.na(ss)){
      
      print(paste("ERROR: at iteration", s, "ss became NA"))
      
      break
      
    }
    
  }
  
  return(ss)
}

basalArea <- function(dbh){
  
 dbh_cm <- dbh*2.54
  ba <- (pi * (dbh_cm/2)^2)/10000
  return(ba)
}

#weighted avg function
weAvg <- function(column1, weights){
  wa <- sum(column1 * weights)
  return(wa)
  
}
```


## Get census data

Should do some kind of weighted average here, not just a basic average.


```{r avg census data}

####Create combined census data
## inflation adjustment: 1.2037 - https://data.bls.gov/cgi-bin/cpicalc.pl?cost1=100.00&year1=201106&year2=202106 
MedHouseInc2011$MedIncome2021Dolars <- as.numeric(MedHouseInc2011$Estimate..Median.household.income.in.the.past.12.months..in.2011.inflation.adjusted.dollars.) * 1.2037

##pull in all information to a combined CensusData file
CensusTracts2010$PercHispLat <- HispLat2011$Estimate..Total..Hispanic.or.Latino[match(CensusTracts2010$geoid10, HispLat2011$geoid10)]/HispLat2011$Estimate..Total[match(CensusTracts2010$geoid10, HispLat2011$geoid10)]
CensusTracts2010$PercWhiteNonHisp <- HispLat2011$Estimate..Total..Not.Hispanic.or.Latino..White.alone[match(CensusTracts2010$geoid10, HispLat2011$geoid10)]/HispLat2011$Estimate..Total[match(CensusTracts2010$geoid10, HispLat2011$geoid10)]
CensusTracts2010$PercBlack <- (HispLat2011$Estimate..Total..Not.Hispanic.or.Latino..Black.or.African.American.alone[match(CensusTracts2010$geoid10, HispLat2011$geoid10)] + HispLat2011$Estimate..Total..Hispanic.or.Latino..Black.or.African.American.alone[match(CensusTracts2010$geoid10, HispLat2011$geoid10)])/HispLat2011$Estimate..Total[match(CensusTracts2010$geoid10, HispLat2011$geoid10)]
CensusTracts2010$MedHouseIncome <- MedHouseInc2011$MedIncome2021Dolars[match(CensusTracts2010$geoid10, MedHouseInc2011$geoid10)]
CensusTracts2010$PercRenter <- HousingTenure2011$Estimate..Total..Renter.occupied[match(CensusTracts2010$geoid10,HousingTenure2011$geoid10)]/HousingTenure2011$Estimate..Total[match(CensusTracts2010$geoid10,HousingTenure2011$geoid10)]
CensusTracts2010$PercMovL5Years <- c(HousingTenure2011$Estimate..Total..Owner.occupied..Moved.in.2005.or.later[match(CensusTracts2010$geoid10,HousingTenure2011$geoid10)] + HousingTenure2011$Estimate..Total..Renter.occupied..Moved.in.2005.or.later[match(CensusTracts2010$geoid10,HousingTenure2011$geoid10)])/HousingTenure2011$Estimate..Total[match(CensusTracts2010$geoid10,HousingTenure2011$geoid10)]

##missing income for 17031280900
CensusTracts2020$PercHispLat <- HispLat2021$Estimate..Total...Hispanic.or.Latino.[match(CensusTracts2020$GEOID, HispLat2021$geoid10)]/HispLat2021$Estimate..Total.[match(CensusTracts2020$GEOID, HispLat2021$geoid10)]
CensusTracts2020$PercWhiteNonHisp <- HispLat2021$Estimate..Total...Not.Hispanic.or.Latino...White.alone[match(CensusTracts2020$GEOID, HispLat2021$geoid10)]/HispLat2021$Estimate..Total.[match(CensusTracts2020$GEOID, HispLat2021$geoid10)]
CensusTracts2020$PercBlack <- (HispLat2021$Estimate..Total...Not.Hispanic.or.Latino...Black.or.African.American.alone[match(CensusTracts2020$GEOID, HispLat2021$geoid10)] + HispLat2021$Estimate..Total...Hispanic.or.Latino...Black.or.African.American.alone[match(CensusTracts2020$GEOID, HispLat2021$geoid10)])/HispLat2021$Estimate..Total.[match(CensusTracts2020$GEOID, HispLat2021$geoid10)]
CensusTracts2020$MedHouseIncome <- MedHouseInc2021$Estimate..Median.household.income.in.the.past.12.months..in.2021.inflation.adjusted.dollars.[match(CensusTracts2020$GEOID, MedHouseInc2021$geoid10)]
CensusTracts2020$PercRenter <- HousingTenure2021$Estimate..Total...Renter.occupied.[match(CensusTracts2020$GEOID, HousingTenure2021$geoid10)]/HousingTenure2021$Estimate..Total.[match(CensusTracts2020$GEOID, HousingTenure2021$geoid10)]
CensusTracts2020$PercMovL5Years <- c(HousingTenure2021$Estimate..Total...Owner.occupied...Moved.in.2019.or.later[match(CensusTracts2020$GEOID, HousingTenure2021$geoid10)] + HousingTenure2021$Estimate..Total...Owner.occupied...Moved.in.2015.to.2018[match(CensusTracts2020$GEOID, HousingTenure2021$geoid10)] +  HousingTenure2021$Estimate..Total...Renter.occupied...Moved.in.2019.or.later[match(CensusTracts2020$GEOID, HousingTenure2021$geoid10)] + HousingTenure2021$Estimate..Total...Renter.occupied...Moved.in.2015.to.2018[match(CensusTracts2020$GEOID, HousingTenure2021$geoid10)])/HousingTenure2021$Estimate..Total.[match(CensusTracts2020$GEOID, HousingTenure2021$geoid10)]

##########################################deal with the census data
CensusTracts2020$SVI <- SVIData$OverallSVI[match(CensusTracts2020$GEOID, SVIData$FIPS)]

##set up weighted average
TotArea2010 <- CensusTracts2010 %>%
  group_by(Name) %>% summarize_at(vars("Area_m2"), sum, na.rm=TRUE)

TotArea2020 <- CensusTracts2020 %>%
  group_by(Name_1) %>% summarize_at(vars("Area_m2"), sum, na.rm=TRUE)

#so now we have the percent of the area for each segment
CensusTracts2010$PercentArea <- CensusTracts2010$Area_m2/TotArea2010$Area_m2[match(CensusTracts2010$Name, TotArea2010$Name)] 
CensusTracts2020$PercentArea <- CensusTracts2020$Area_m2/TotArea2020$Area_m2[match(CensusTracts2020$Name_1, TotArea2020$Name_1)] 

finalCensusCols <- c("Segment", "PercHispanicLatine11","PercHispanicLatine21", "PercBlack11","PercBlack21", "PercWhiteNonHL11", "PercWhiteNonHL21", "MedHouseInc11","MedHouseInc21", "PercRent11","PercRent21", "PercRMov11","PercRMov21", "SVI")
SegmentCensusData <- as.data.frame(matrix(NA, nrow=length(TotArea2010$Name), ncol=length(finalCensusCols)))
names(SegmentCensusData) <- finalCensusCols

#get the weighted average
for (s in 1:length(TotArea2010$Name)){
  
  seg <- TotArea2010$Name[s]
  
  #get your segment data
  sdata2010 <- CensusTracts2010[CensusTracts2010$Name == seg, ]
  sdata2020 <- CensusTracts2020[CensusTracts2020$Name_1 == seg, ]
  sdata2020$MedHouseIncome <- as.numeric(sdata2020$MedHouseIncome)
  SegmentCensusData$Segment[s] <- seg
  
  # 2011
  SegmentCensusData[s, c("PercHispanicLatine11", "PercBlack11", "PercWhiteNonHL11", 
                         "MedHouseInc11", "PercRent11",  "PercRMov11")] <- sapply(sdata2010[,c("PercHispLat", "PercBlack", "PercWhiteNonHisp", "MedHouseIncome", "PercRenter","PercMovL5Years")], weAvg, weights=sdata2010$PercentArea)
    
  
  ###########Check for NAs
  if (length(na.omit(sdata2020$MedHouseIncome)) < length(sdata2020$MedHouseIncome)){
    
    ###the only NA so far is in income
    incdata <- na.omit(sdata2020$MedHouseIncome)
    adjustdata <- sdata2020$PercentArea[!is.na(sdata2020$MedHouseIncome)]/sum(sdata2020$PercentArea[!is.na(sdata2020$MedHouseIncome)])
    
    SegmentCensusData$MedHouseInc21[s] <- sum(incdata * adjustdata)
    
    SegmentCensusData[s, c("PercHispanicLatine21", "PercBlack21", "PercWhiteNonHL21", 
                         "PercRent21",  "PercRMov21", "SVI")] <- sapply(sdata2020[,c("PercHispLat", "PercBlack", "PercWhiteNonHisp", "PercRenter","PercMovL5Years", "SVI")], weAvg, weights=sdata2020$PercentArea)
    
    
  } else { #########no NAs
    #2021
  SegmentCensusData[s, c("PercHispanicLatine21", "PercBlack21", "PercWhiteNonHL21", 
                         "MedHouseInc21", "PercRent21",  "PercRMov21", "SVI")] <- sapply(sdata2020[,c("PercHispLat", "PercBlack", "PercWhiteNonHisp", "MedHouseIncome", "PercRenter","PercMovL5Years", "SVI")], weAvg, weights=sdata2020$PercentArea)
    
  }

  

}

#change one segment name
SegmentCensusData$Segment[SegmentCensusData$Segment == "260/275"] <- "275"

```


##Get Building and Zoning Averages

```{r building and zoning averages}
##########################################Building data
#permitting information
BPerm$Year_issued <- format(as.Date(BPerm$PermitIssueDate, "%m/%d/%Y"), "%Y")
BPerm <- BPerm[!is.na(BPerm$Year_issued),]

#get some easy tables to reference
perm_typs <- table(BPerm[,c("Segment", "PermitType")])
perm_yrs_const <- table(BPerm[BPerm$PermitType == "NewConst", c("Segment", "Year_issued")])
perm_yrs_reno <- table(BPerm[BPerm$PermitType == "Reno_Alt_add", c("Segment", "Year_issued")])

##create data frame to combine them all
BuiComb_nms <- c("Segment", "NumBuild", "NumConst_since11", "NumReno_since11", "NumConst_since15", "NumReno_since15", "NumDemo")
Seg_building <- as.data.frame(matrix(0, nrow=14, ncol=length(BuiComb_nms)))
names(Seg_building) <- BuiComb_nms

##building counts
BuiCount <- table(BFoot[,c("Name")])

#start filling out the combined dataframe
Seg_building$Segment <- names(BuiCount)
Seg_building$NumBuild <- BuiCount[match(Seg_building$Segment, names(BuiCount))]
Seg_building$NumConst_since11[match(rownames(perm_yrs_const), Seg_building$Segment)] <- rowSums(perm_yrs_const[,c("2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")])
Seg_building$NumReno_since11[match(rownames(perm_yrs_reno), Seg_building$Segment)] <- rowSums(perm_yrs_reno[,c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")])
Seg_building$NumConst_since15[match(rownames(perm_yrs_const), Seg_building$Segment)]  <- rowSums(perm_yrs_const[,c("2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")])
Seg_building$NumReno_since15[match(rownames(perm_yrs_reno), Seg_building$Segment)]  <- rowSums(perm_yrs_reno[,c( "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")])
Seg_building$NumDemo[Seg_building$Segment == 244] <- 1

###########################Zoning Data
#######Get the data for a weighted average
TotArea <- ZoningData %>% 
  group_by(Name) %>%
  summarize_at(vars("Area_m2"), sum, na.rm=TRUE)

#get simplified zones to use
ZoningData$SimplifiedCat <- ZoningDescr$SimplifiedCategory[match(ZoningData$zone_class, ZoningDescr$zone_class)]
#ZoningData$SimplifiedCat[ZoningData$zone_type == 5] <- "Other"
ZoningData$SimplifiedCat[ZoningData$zone_type == 12] <- "Park"

#dataframe to combine them all
zoning_cols <- c("Segment", "PercRes_z", "PercComm_z", "PercInd_z", "PercInst_z", "PercPark_z")
Zoning_bySeg <- as.data.frame(matrix(0, nrow=13, ncol=length(zoning_cols)))
names(Zoning_bySeg) <- zoning_cols

#get area for each zone in each segment
AreaBySimpleZone <- ZoningData %>% 
  group_by(Name, SimplifiedCat) %>%
  summarize_at(vars("Area_m2"), sum, na.rm=TRUE)

AreaBySimpleZone <- AreaBySimpleZone[!is.na(AreaBySimpleZone$SimplifiedCat),]
Zns <- c("Residential", "Commercial", "Industrial", "Institutional", "Park")
segs <- na.omit(unique(AreaBySimpleZone$Name))
segs <- segs[segs != "268"]

#go through and get your averages
for (s in 1:length(segs)){
  
  sg <- segs[s]
  sdata <- na.omit(AreaBySimpleZone[AreaBySimpleZone$Name == sg,])
  Zoning_bySeg$Segment[s] <- sg
  Zoning_bySeg[s,(match(unique(sdata$SimplifiedCat), Zns) + 1)] <- sdata$Area_m2/TotArea$Area_m2[TotArea$Name == sg]
}

#to make it simpler later to combine data
Zoning_bySeg$Segment[Zoning_bySeg$Segment == "260/275"] <- "275"

```



##Get species data to pull in

```{r get species information}
#a little more intuitive
names(TreeLvlCombined)[names(TreeLvlCombined) == "CrownVigor"] <- "CrownStress"

#for ease later
TreeLvlCombined$GenSpe <- paste(TreeLvlCombined$Genus, TreeLvlCombined$Species, sep="_")

#To line up with species info
TreeLvlCombined$Species[TreeLvlCombined$Species == "unknown"] <- "spp."
TreeLvlCombined[, c("DroughtTol", "SaltTol", "UrbanApp")] <- rep(NA, length(TreeLvlCombined$TreeName))

##for a few weird species
londonplane <- c("x acerifolia", "hybrida")
TreeLvlCombined$Species[TreeLvlCombined$Species %in% londonplane] <- "x hispanica"
TreeLvlCombined$Species[TreeLvlCombined$Species == "sylvatica"] <- "silvatica" #for Nyssa silvatica

#row by row
for (t in 1:length(TreeLvlCombined$X)){
  YesGen <- SppSpecificData$SUB_GENUS == TreeLvlCombined$Genus[t]
  YesSpp <- SppSpecificData$SUB_SPECIES == TreeLvlCombined$Species[t]
  
  SppInfoInd <- c(1:length(SppSpecificData[,1]))[(YesGen & YesSpp)]
  
  #what do you do if you don't have info on this species
  if(length(SppInfoInd) == 0){
    print(paste("Error, no species information for", TreeLvlCombined$GenSpe[t], "Tree #", t))
    
    ##try to fill it in with the default for the genus
    Spp2 <- SppSpecificData$SUB_SPECIES =="spp."
    SppInfoInd2 <- c(1:length(SppSpecificData[,1]))[(YesGen & Spp2)]
    
    if(length(SppInfoInd2) == 0){
      print(paste("Error, no generic genus-level information for", TreeLvlCombined$Genus[t], "Tree #", t))
      next #go to the next tree
    } else {
      TreeLvlCombined$DroughtTol[t] <- SppSpecificData$DroughtTol[SppInfoInd2]
      TreeLvlCombined$SaltTol[t] <- SppSpecificData$SaltTol[SppInfoInd2]
      TreeLvlCombined$UrbanApp[t] <- SppSpecificData$StreetUrban[SppInfoInd2]
    }
  
  #have a species-level match
  } else {
    TreeLvlCombined$DroughtTol[t] <- SppSpecificData$DroughtTol[SppInfoInd]
    TreeLvlCombined$SaltTol[t] <- SppSpecificData$SaltTol[SppInfoInd]
    TreeLvlCombined$UrbanApp[t] <- SppSpecificData$StreetUrban[SppInfoInd]
  } #seeing if there is a match
  
}

##Species group adjustment
TreeLvlCombined$GenSpe[TreeLvlCombined$GenSpe == "Fraxinus_pennsylvanica" | TreeLvlCombined$GenSpe == "Fraxinus_unknown"] <- "Fraxinus spp."
TreeLvlCombined$GenSpe[(TreeLvlCombined$GenSpe == "Tilia_cordata") | (TreeLvlCombined$GenSpe == "Tilia_americana")] <- "Tilia spp." #small sample size and some cultivars
TreeLvlCombined$GenSpe[TreeLvlCombined$GenSpe == "Ulmus_americana"] <- "Ulmus spp." #unsure IDs
TreeLvlCombined$GenSpe[TreeLvlCombined$GenSpe == "Ulmus_pumila"| TreeLvlCombined$GenSpe == "Ulmus_unknown"] <- "Ulmus spp." #unsure IDs
SppFreq <- sort(table(TreeLvlCombined$GenSpe),decreasing = TRUE)
CommonSpp <- SppFreq[SppFreq > 50]

#Create a species group category
TreeLvlCombined$SppGroup <- rep("Other", length(TreeLvlCombined$TreeName))
TreeLvlCombined$SppGroup[TreeLvlCombined$GenSpe %in% names(CommonSpp)] <- TreeLvlCombined$GenSpe[TreeLvlCombined$GenSpe %in% names(CommonSpp)]
TreeLvlCombined$SppGroup <- as.factor(TreeLvlCombined$SppGroup) #for model
TreeLvlCombined$SppGroup <- relevel(TreeLvlCombined$SppGroup, ref = "Other")

##make a genus-lvl grouping 
TreeLvlCombined$GenusGroup <- TreeLvlCombined$Genus
GenusFreq <- table(TreeLvlCombined$Genus)
GenusFreq <- GenusFreq[GenusFreq > 40]
TreeLvlCombined$GenusGroup[!(TreeLvlCombined$GenusGroup %in% names(GenusFreq))] <- "01_Other"
TreeLvlCombined$GenusGroup <- as.factor(TreeLvlCombined$GenusGroup )
TreeLvlCombined$GenusGroup <- relevel(TreeLvlCombined$GenusGroup, ref = "01_Other")

```

##start to clean up tree-level data

Going through and making sure the format of the data matches that of Kamakura et al. (under review)

```{r prep response data}
#Get rid of trees without local site conditions
TreeLvlCombined <- TreeLvlCombined[!is.na(TreeLvlCombined$Gardenscape),]

#convert dbh to basal area
TreeLvlCombined$BasalArea <- sapply(TreeLvlCombined$TotalDBH, basalArea) 

#Year
TreeLvlCombined$Year <- as.factor(TreeLvlCombined$Year)

#########################################Tree stress variables
#collapsing the categories here for ease
TreeLvlCombined$Dieback[((TreeLvlCombined$Dieback > 3) & (TreeLvlCombined$Dieback <= 6))] <- 4 #11-25%
TreeLvlCombined$Dieback[(TreeLvlCombined$Dieback > 6)] <- 5 #25%+
TreeLvlCombined$Dieback[TreeLvlCombined$CrownStress >= 5] <- 5 #trees are dead
TreeLvlCombined$Defoliation[TreeLvlCombined$Defoliation > 3] <- 3 #not enough variation (26%+)
TreeLvlCombined$Discoloration[TreeLvlCombined$Discoloration > 4] <- 4 #not enough variation (50%+)

#Get rid of 0.5 (that comes from the averages)
TreeLvlCombined$Discoloration <- round(TreeLvlCombined$Discoloration)
TreeLvlCombined$Defoliation <- round(TreeLvlCombined$Defoliation)
TreeLvlCombined$Dieback <- round(TreeLvlCombined$Dieback)

##CrownStress
TreeLvlCombined$CrownStress <- round(TreeLvlCombined$CrownStress, digits=0)

################################################Cues to care
##create Mulch categories
TreeLvlCombined$Mulch[TreeLvlCombined$Mulch == 1] <- "Mulch"
TreeLvlCombined$Mulch[TreeLvlCombined$Mulch == 0] <- "None"
TreeLvlCombined$Mulch[TreeLvlCombined$MulchVolcano == 1] <- "Volcano"

TreeLvlCombined$Mulch <- as.factor(TreeLvlCombined$Mulch)
TreeLvlCombined$Mulch <- relevel(TreeLvlCombined$Mulch, ref = "None")

##Simplify to a binary variable
TreeLvlCombined$CorrMulch <- TreeLvlCombined$Mulch
TreeLvlCombined$CorrMulch <- as.character(TreeLvlCombined$CorrMulch)
TreeLvlCombined$CorrMulch[TreeLvlCombined$CorrMulch == "Mulch"] <- 1
TreeLvlCombined$CorrMulch[TreeLvlCombined$CorrMulch != 1] <- 0

#Translate Gardenscape
TreeLvlCombined$Gardenscape[TreeLvlCombined$Gardenscape==""] <- "None"
h1 <- c("None", "Minimal", "Moderate", "Extensive")
h2 <- c(2:4,4)
GDict <- as.data.frame(matrix(c(h1,h2), nrow=4, ncol=2, byrow=FALSE))
names(GDict) <- c("Original", "Simplified")

TreeLvlCombined$Gardenscape <- GDict$Simplified[match(TreeLvlCombined$Gardenscape, GDict$Original)]
TreeLvlCombined$Gardenscape[TreeLvlCombined$Gardenscape == 2 & TreeLvlCombined$Mowing %in% c("old", "potentially never")] <- 1
TreeLvlCombined$Gardenscape <- as.factor(TreeLvlCombined$Gardenscape)

#Pruning
TreeLvlCombined$PrunedCorrect <-TreeLvlCombined$Pruned
TreeLvlCombined$PrunedCorrect[TreeLvlCombined$HatrackPrune == 1 | TreeLvlCombined$FlushCutPrune == 1] <- 0


###################################################Site condition variables

##Group Land Use categories
TreeLvlCombined$LandUse <- as.character(TreeLvlCombined$LandUse)
TreeLvlCombined$LandUse[TreeLvlCombined$LandUse == "SFR-A" | TreeLvlCombined$LandUse == "SFR-D"] <- "SFR"
TreeLvlCombined$LandUse[TreeLvlCombined$LandUse == "COMM" | TreeLvlCombined$LandUse == "MIX"] <- "COMM_Mx"
TreeLvlCombined$LandUse[TreeLvlCombined$LandUse == "V" | TreeLvlCombined$LandUse == "UT" | TreeLvlCombined$LandUse == "IND" | TreeLvlCombined$LandUse == "UT" | TreeLvlCombined$LandUse == "TR" | TreeLvlCombined$LandUse == "AG" | TreeLvlCombined$LandUse == "INST"| TreeLvlCombined$LandUse == "MP"] <- "Other"
TreeLvlCombined$LandUse <- as.factor(TreeLvlCombined$LandUse)
TreeLvlCombined$LandUse <- relevel(TreeLvlCombined$LandUse, ref = "Other")

##Need to modify the Percent Imperv because some of the categories are very infrequent
TreeLvlCombined$PercentImperv[TreeLvlCombined$PercentImperv <=2] <- 1 #less than 26% imperv
TreeLvlCombined$PercentImperv[TreeLvlCombined$PercentImperv ==3] <- 2 #26-50
TreeLvlCombined$PercentImperv[TreeLvlCombined$PercentImperv ==4] <- 3 #51-75
TreeLvlCombined$PercentImperv[TreeLvlCombined$PercentImperv ==5] <- 4 #76-100
TreeLvlCombined$PercentImperv <- as.factor(TreeLvlCombined$PercentImperv)

#Site type - simplify due to lack of variation
TreeLvlCombined$SiteType <- as.character(TreeLvlCombined$SiteType)
TreeLvlCombined$SiteType[is.null(TreeLvlCombined$SiteType) |TreeLvlCombined$SiteType== ""| TreeLvlCombined$SiteType== "MP" | TreeLvlCombined$SiteType == "OM" | TreeLvlCombined$SiteType == "OH"] <- "Other"
TreeLvlCombined$SiteType <- as.factor(TreeLvlCombined$SiteType)
TreeLvlCombined$SiteType <- relevel(TreeLvlCombined$SiteType, ref="SC")


```


## Convert to segment-level tree data

```{r pull in tree data}

##create a dataframe to storedata
colsSto <- names(TreeLvlCombined)
uniTrees <- unique(TreeLvlCombined$TreeName)
UniqueTreeData <- as.data.frame(matrix(0, ncol=length(colsSto), nrow = length(uniTrees)))
names(UniqueTreeData) <- colsSto

#get a version of the data to work with (easier to fix errors)
TreeData_SegLvl <- TreeLvlCombined

#change the formatting to be able to modify
TreeData_SegLvl$Year <- as.numeric(as.character(TreeData_SegLvl$Year))
TreeData_SegLvl$LandUse <- as.character(TreeData_SegLvl$LandUse)
TreeData_SegLvl$SiteType <- as.character(TreeData_SegLvl$SiteType)

#iterator
MatInd <- 1

#get one row per tree
for (u in 1:length(uniTrees)){
  
  treeName <- uniTrees[u]
  treedata <- TreeData_SegLvl[TreeData_SegLvl$TreeName == treeName,]
  
  mostRecYr <- max(treedata$Year)
  
  Dat2Use <- treedata[treedata$Year == mostRecYr, ]
  
  UniqueTreeData[MatInd,] <- Dat2Use[1,]
  
  MatInd <- MatInd + 1
  
}

##set up data for diversity indices - first at the species level
UniqueTreeData <- UniqueTreeData[UniqueTreeData$Segment != "UIC",] #get rid of the baseline data
UniqueTreeData$CorrMulch <- as.numeric(UniqueTreeData$CorrMulch)

SppSeg <- table(UniqueTreeData[, c("Segment", "GenSpe")]) #check about these species IDs
#shannonDivSegs <- diversity(SppSeg, index="shannon")
simpsonDivSegs <- diversity(SppSeg, index="simpson")

#now at the level of genera
GenSeg <- table(UniqueTreeData[, c("Segment", "Genus")])
#shannonDivSegs_gen <- diversity(GenSeg, index="shannon")
simpsonDivSegs_gen <- diversity(GenSeg, index="simpson")


SegAvg_UniqueDat <- UniqueTreeData %>%
  group_by(Segment) %>%
  summarize_at(vars("BasalArea", "CrownLight", "CorrMulch", "PrunedCorrect", "UrbanApp", "TrunkDamage", "TreeGuard"), mean, na.rm=TRUE)

TotalSegTrees <- table(UniqueTreeData$Segment)

#Site Type
Seg_SiteType_Counts <- table(UniqueTreeData[,c("Segment", "SiteType")])
Perc_SegST <- sweep(Seg_SiteType_Counts, 1, TotalSegTrees, FUN='/')
#from this, probably most useful to look at percent SC or SP and then Percent FY or SY
#with mod, use SP, SC, Yard

#Land Use
Seg_LandUse_Counts <- table(UniqueTreeData[,c("Segment", "LandUse")])
Perc_SegLU <- sweep(Seg_LandUse_Counts, 1, TotalSegTrees, FUN='/')
#here, look at Res vs COMM

#Percent Impervious
Seg_PI_Counts <- table(UniqueTreeData[,c("Segment", "PercentImperv")])
Perc_SegPI <- sweep(Seg_PI_Counts, 1, TotalSegTrees, FUN='/')
#kind of like your analyses, maybe combine 1 and 2, then 3, then 4 and 5 combined

#Gardenscape
Seg_Gardenscape_Counts <- table(UniqueTreeData[,c("Segment", "Gardenscape")])
Perc_SegGard <- sweep(Seg_Gardenscape_Counts, 1, TotalSegTrees, FUN='/')
#use whatever you used in the analyses above
#do 1, 2, 3+?, or maybe do 1 and 4/5 and leave the rest to be moderate?

#Tree Health
#should use the same groupings as I did for the analyses above
#for these it is probably worth pulling in all the cateories to start with and adjust as needed
#maybe ignore defoliation because you only have 2 categories?
Seg_Discol_Counts <- table(UniqueTreeData[,c("Segment", "Discoloration")])
Perc_SegDisc <- sweep(Seg_Discol_Counts, 1, TotalSegTrees, FUN='/')
Seg_Defol_Counts <- table(UniqueTreeData[,c("Segment", "Defoliation")])
Perc_SegDef <- sweep(Seg_Defol_Counts, 1, TotalSegTrees, FUN='/')
Seg_DBK_Counts <- table(UniqueTreeData[,c("Segment", "Dieback")])
Perc_SegDBK <- sweep(Seg_DBK_Counts, 1, TotalSegTrees, FUN='/')
Seg_CS_Counts <- table(UniqueTreeData[,c("Segment", "CrownStress")])
Perc_SegCS <- sweep(Seg_CS_Counts, 1, TotalSegTrees, FUN='/')
Seg_UrbanApp_Counts <- table(UniqueTreeData[,c("Segment", "UrbanApp")])
Perc_SegUA <- sweep(Seg_UrbanApp_Counts, 1, TotalSegTrees, FUN='/')

##################################################Combine all the data
nrows <- length(SegmentCensusData$Segment)
SegDatCols <- c("Segment","AvgBA", "PercCorrMulch", "PercUrbanApp", "PercResTree", "PercCOMM_MxTree", "PercSC", "PercGar3o4", "PercDisc3o4", "PercDBK5", "PercCS4o5", "SimpsonsDivSpp", "SimpsonsDivGen", "totNumTrees")
SegmentLvlDat <- as.data.frame(matrix(NA, nrow=nrows, ncol=length(SegDatCols)))
names(SegmentLvlDat) <- SegDatCols

SegNms <- unique(SegmentCensusData$Segment)


##Add census data to empty df
for(s in 1:length(SegNms)){
  
  seg <- SegNms[s]
  SegmentLvlDat$Segment[s] <- seg

  ####Pull in the non-census data
  SegInd_treed <- match(seg, SegAvg_UniqueDat$Segment)
  
  SegmentLvlDat$AvgBA[s] <- SegAvg_UniqueDat$BasalArea[SegInd_treed]
  SegmentLvlDat$PercUrbanApp[s] <- SegAvg_UniqueDat$UrbanApp[SegInd_treed]
  SegmentLvlDat$PercCorrMulch[s] <- SegAvg_UniqueDat$CorrMulch[SegInd_treed]
  SegmentLvlDat$PercGar3o4[s] <- Perc_SegGard[SegInd_treed,match("3", colnames(Perc_SegGard))] + Perc_SegGard[SegInd_treed,match("4", colnames(Perc_SegGard))]
  
  ##have to pull from other summaries
  SegmentLvlDat$PercResTree[s] <- Perc_SegLU[SegInd_treed, ("MFR")] +  Perc_SegLU[SegInd_treed, ("SFR")]
  SegmentLvlDat$PercCOMM_MxTree[s] <- Perc_SegLU[SegInd_treed, ("COMM_Mx")]
  SegmentLvlDat$PercSC[s] <- Perc_SegST[SegInd_treed, match("SC", colnames(Perc_SegST))]
  
  
  #tree health outcomes
  SegmentLvlDat$PercDisc3o4[s] <- Perc_SegDisc[SegInd_treed, match("3", colnames(Perc_SegDisc))] + Perc_SegDisc[SegInd_treed, match("4", colnames(Perc_SegDisc))]
  SegmentLvlDat$PercDBK5[s] <- Perc_SegDBK[SegInd_treed, match("5", colnames(Perc_SegDBK))]
  SegmentLvlDat$PercCS4o5[s] <- Perc_SegCS[SegInd_treed, match("4", colnames(Perc_SegCS))] + Perc_SegCS[SegInd_treed, match("5", colnames(Perc_SegCS))]
  
  ##Diversity
  SegmentLvlDat$SimpsonsDivSpp[s] <- as.vector(simpsonDivSegs[match(seg, names(simpsonDivSegs))])
  SegmentLvlDat$SimpsonsDivGen[s]<- as.vector(simpsonDivSegs_gen[match(seg, names(simpsonDivSegs_gen))])
  
  #basic info
  SegmentLvlDat$totNumTrees[s] <- table(UniqueTreeData[,c("Segment")])[SegInd_treed]
  
}

SegmentLvlDat <- SegmentLvlDat[!is.na(SegmentLvlDat$Segment),]


```


##Combine all seg-lvl data

```{r combine all data}

#get rid of segment 268
SegmentCensusData <- SegmentCensusData[SegmentCensusData$Segment != "268",]
Seg_building <- Seg_building[Seg_building$Segment != "268",]
Seg_building$Segment[Seg_building$Segment == "260/275"] <- "275"
SegmentLvlDat <- SegmentLvlDat[SegmentLvlDat$Segment != "268",]

Seg_allData <- cbind(SegmentLvlDat, Zoning_bySeg, Seg_building, SegmentCensusData)

#add a few last columns
Seg_allData$Change_PHL <- Seg_allData$PercHispanicLatine21 - Seg_allData$PercHispanicLatine11
Seg_allData$Change_PBl <- Seg_allData$PercBlack21 - Seg_allData$PercBlack11
Seg_allData$Change_PWnHL <- Seg_allData$PercWhiteNonHL21 - Seg_allData$PercWhiteNonHL11
Seg_allData$Change_MedHHI <- Seg_allData$MedHouseInc21 - Seg_allData$MedHouseInc11
SegmentCensusData$Avg_PRent <- (SegmentCensusData$PercRent21 + SegmentCensusData$PercRent11)/2
SegmentCensusData$Avg_Rmov <- (SegmentCensusData$PercRMov21 + SegmentCensusData$PercRMov11)/2

##add census data for change over time (percent change)

AnalysisCols <- c("PercComm_z", "PercSC", "PercGar3o4", "PercCorrMulch", "AvgBA","PercUrbanApp",  "PercDisc3o4", "PercDBK5", "PercCS4o5")

#go through and slightly adjust the variables that will be modeled with a beta distribution
#you can't have exact 0's or 1's
for(c in 1:length(AnalysisCols)){
  
  v <- AnalysisCols[c]
  v_ind <- match(v, names(Seg_allData))
  
  Seg_allData[(Seg_allData[,v_ind] == 0) ,v_ind] <- 0.0001
  Seg_allData[(Seg_allData[,v_ind] == 1) ,v_ind] <- 0.9999
  
}

#######################################################################################################

###Use to translate from the labels from the grids to labels in paper

########More of an FYI for anyone reading this later
# InitialSegNames <- c("49", "157", "55", "153", "244", 
#             "275", "57", "128", "292", "281",
#             "306", "324", "16")
# PaperSegNames <- c(12, 13, 10, 11, 7,
#                    9, 6, 8, 5, 4,
#                    2, 3, 1)
# 
# Seg_allData$Segment[match(Seg_allData$Segment, InitialSegNames)] <- PaperSegNames[match(Seg_allData$Segment, InitialSegNames)]

write.csv(Seg_allData, "../01Data/Chicago/ChicagoSegmentData.csv")

```

