---
title: "Durham Data Cleaning"
output: html_document
date: "2024-08-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

##Group means for segment data
library(dplyr)

##Visuals
library(ggplot2)

##dataframe manipulation
library(dplyr)

#for your diversity metrics
library(vegan)

```

```{r read in tree lvl data}

#read in full version of the tree dataset
TreeLvlCombined <- read.csv("../01Data/Durham/091523AllYearsCombDurham.csv")

TodayDate <- Sys.Date()
date <- format(TodayDate, format="%b%d%y")

##get the new data
BuildingPermits <- read.csv("../01Data/Durham/Durham_BuildingPermits_wSeg_clean.csv")
BuildingParcels <- read.csv("../01Data/Durham/DurhamBuildings_Segs_fix.csv")

#census
CensusTracts2010 <- read.csv("../01Data/Durham/Durham2010Census_bySeg_fix.csv")
CensusTracts2020 <- read.csv("../01Data/Durham/Durham2020Census_bySeg_fix.csv")
SVIData <- read.csv("../01Data/Durham/SVI_Durham.csv")
HispLat2011 <- read.csv("../01Data/Durham/Durham_HispLat_ACS2011.csv")
HispLat2021 <- read.csv("../01Data/Durham/Durham_HispLat_ACS2021.csv")
MedHouseInc2011 <- read.csv("../01Data/Durham/Durham_MedHousIncome_ACS2011_2011InflAdj.csv")
MedHouseInc2021 <- read.csv("../01Data/Durham/Durham_MedHousIncome_ACS2021_2021InflAdj.csv")
HousingTenure2011 <- read.csv("../01Data/Durham/Durham_HousingTenure_ACS2011.csv")
HousingTenure2021 <- read.csv("../01Data/Durham/Durham_HousingTenure_ACS2021.csv")

#tree species information
SppSpecificData <- read.csv("../01Data/Durham/DurhamSpeciesInfo_Dirr.csv")

#zoning
ZoningDat  <- read.csv("../01Data/Durham/DurhamZoning_bySeg_fix.csv")

```


##Useful Functions
```{r useful funcs}
sumSquares <- function(predicted, actual){
  
  ss <- 0
  
  for(s in 1:length(predicted)){
    
    ss <- ss + (predicted[s] - actual[s])^2
    
    if( is.na(ss)){
      
      print(paste("ERROR: at iteration", s, "ss became NA"))
      
      break
      
    }
    
  }
  
  return(ss)
}

basalArea <- function(dbh){
  
 dbh_cm <- dbh*2.54
  ba <- (pi * (dbh_cm/2)^2)/10000
  return(ba)
}

#weighted avg function
weAvg <- function(column1, weights){
  wa <- sum(column1 * weights)
  return(wa)
  
}
```


#####Manage Census Data
```{r get census data}

##########################################deal with the census data
CensusTracts2020$SVI <- SVIData$OverallSVI[match(CensusTracts2020$GEOID, SVIData$FIPS)]

####Create combined census data
## inflation adjustment: 1.2037 - https://data.bls.gov/cgi-bin/cpicalc.pl?cost1=100.00&year1=201106&year2=202106 
MedHouseInc2011$MedIncome2021Dolars <- as.numeric(MedHouseInc2011$Median.household.income.in.the.past.12.months..in.2011.inflation.adjusted.dollars.) * 1.2037

##get just the estimates
HispLat2011_est <- HispLat2011[HispLat2011$Label..Grouping. == "Estimate",]
HispLat2021_est <- HispLat2021[HispLat2021$ValueType == "Estimate",]
MedHouseInc2011_est <- MedHouseInc2011[MedHouseInc2011$Label..Grouping. == "Estimate",]
MedHouseInc2021_est <- MedHouseInc2021[MedHouseInc2021$Label..Grouping. == "Estimate",] 
HousingTenure2011_est <- HousingTenure2011[HousingTenure2011$Label..Grouping. == "Estimate",]
HousingTenure2021_est <- HousingTenure2021[HousingTenure2021$Label..Grouping. == "Estimate",]

#######################################2011 data
CensusTracts2010$PercHispLat <- as.numeric(HispLat2011_est$Total...Hispanic.or.Latino.[match(CensusTracts2010$LOCATION, HispLat2011_est$Census.Tract)])/as.numeric(HispLat2011_est$Total.[match(CensusTracts2010$LOCATION, HispLat2011_est$Census.Tract)])

CensusTracts2010$PercWhiteNonHisp <- as.numeric(HispLat2011_est$Total...Not.Hispanic.or.Latino...White.alone[match(CensusTracts2010$LOCATION, HispLat2011_est$Census.Tract)])/as.numeric(HispLat2011_est$Total.[match(CensusTracts2010$LOCATION, HispLat2011_est$Census.Tract)])

CensusTracts2010$PercBlack <- (as.numeric(HispLat2011_est$Total...Not.Hispanic.or.Latino...Black.or.African.American.alone[match(CensusTracts2010$LOCATION, HispLat2011_est$Census.Tract)]) + as.numeric(HispLat2011_est$Total...Hispanic.or.Latino...Black.or.African.American.alone[match(CensusTracts2010$LOCATION, HispLat2011_est$Census.Tract)]))/as.numeric(HispLat2011_est$Total.[match(CensusTracts2010$LOCATION, HispLat2011_est$Census.Tract)])

CensusTracts2010$MedHouseIncome <- as.numeric(MedHouseInc2011_est$MedIncome2021Dolars[match(CensusTracts2010$LOCATION, MedHouseInc2011_est$Census.Tract)])

CensusTracts2010$PercRenter <- as.numeric(HousingTenure2011_est$Total...Renter.occupied.[match(CensusTracts2010$LOCATION,HousingTenure2011_est$Census.Tract)])/as.numeric(HousingTenure2011_est$Total.[match(CensusTracts2010$LOCATION,HousingTenure2011_est$Census.Tract)])

CensusTracts2010$PercMovL5Years <- c(as.numeric(HousingTenure2011_est$Total...Owner.occupied...Moved.in.2005.or.later[match(CensusTracts2010$LOCATION,HousingTenure2011_est$Census.Tract)]) + as.numeric(HousingTenure2011_est$Total...Renter.occupied...Moved.in.2005.or.later[match(CensusTracts2010$LOCATION,HousingTenure2011_est$Census.Tract)]))/as.numeric(HousingTenure2011_est$Total.[match(CensusTracts2010$LOCATION,HousingTenure2011_est$Census.Tract)])



###############################################2021 data
CensusTracts2020$PercHispLat <- as.numeric(HispLat2021_est$Total...Hispanic.or.Latino.[match(CensusTracts2020$NAMELSAD, HispLat2021_est$CensusTract)])/as.numeric(HispLat2021_est$Total.[match(CensusTracts2020$NAMELSAD, HispLat2021_est$CensusTract)])

CensusTracts2020$PercWhiteNonHisp <- as.numeric(HispLat2021_est$Total...Not.Hispanic.or.Latino...White.alone[match(CensusTracts2020$NAMELSAD, HispLat2021_est$CensusTract)])/as.numeric(HispLat2021_est$Total.[match(CensusTracts2020$NAMELSAD, HispLat2021_est$CensusTract)])

CensusTracts2020$PercBlack <- (as.numeric(HispLat2021_est$Total...Not.Hispanic.or.Latino...Black.or.African.American.alone[match(CensusTracts2020$NAMELSAD, HispLat2021_est$CensusTract)]) + as.numeric(HispLat2021_est$Total...Hispanic.or.Latino...Black.or.African.American.alone[match(CensusTracts2020$NAMELSAD, HispLat2021_est$CensusTract)]))/as.numeric(HispLat2021_est$Total.[match(CensusTracts2020$NAMELSAD, HispLat2021_est$CensusTract)])

CensusTracts2020$MedHouseIncome <- as.numeric(MedHouseInc2021$Median.household.income.in.the.past.12.months..in.2021.inflation.adjusted.dollars.[match(CensusTracts2020$NAMELSAD, MedHouseInc2021$Census.Tract)])

CensusTracts2020$PercRenter <- as.numeric(HousingTenure2021_est$Total...Renter.occupied.[match(CensusTracts2020$NAMELSAD, HousingTenure2021_est$Census.Tract)])/as.numeric(HousingTenure2021_est$Total.[match(CensusTracts2020$NAMELSAD, HousingTenure2021_est$Census.Tract)])

CensusTracts2020$PercMovL5Years <- c(as.numeric(HousingTenure2021_est$Total...Owner.occupied...Moved.in.2019.or.later[match(CensusTracts2020$NAMELSAD, HousingTenure2021_est$Census.Tract)]) + as.numeric(HousingTenure2021_est$Total...Renter.occupied...Moved.in.2019.or.later[match(CensusTracts2020$NAMELSAD, HousingTenure2021_est$Census.Tract)]) + as.numeric(HousingTenure2021_est$Total...Owner.occupied...Moved.in.2015.to.2018[match(CensusTracts2020$NAMELSAD, HousingTenure2021_est$Census.Tract)]) + as.numeric(HousingTenure2021_est$Total...Renter.occupied...Moved.in.2015.to.2018[match(CensusTracts2020$NAMELSAD, HousingTenure2021_est$Census.Tract)]))/as.numeric(HousingTenure2021_est$Total.[match(CensusTracts2020$NAMELSAD, HousingTenure2021_est$Census.Tract)])

##set up weighted average
TotArea2010 <- CensusTracts2010 %>%
  group_by(Name) %>% summarize_at(vars("Area_m2"), sum, na.rm=TRUE)

TotArea2020 <- CensusTracts2020 %>%
  group_by(Name_1) %>% summarize_at(vars("Area_m2"), sum, na.rm=TRUE)


#so now we have the percent of the area for each segment
CensusTracts2010$PercentArea <- CensusTracts2010$Area_m2/TotArea2010$Area_m2[match(CensusTracts2010$Name, TotArea2010$Name)] 
CensusTracts2020$PercentArea <- CensusTracts2020$Area_m2/TotArea2020$Area_m2[match(CensusTracts2020$Name_1, TotArea2020$Name_1)] 

finalCensusCols <- c("Segment", "PercHispanicLatine11","PercHispanicLatine21", "PercBlack11","PercBlack21", "PercWhiteNonHL11", "PercWhiteNonHL21", "MedHouseInc11","MedHouseInc21", "PercRent11","PercRent21", "PercRMov11","PercRMov21", "SVI")
SegmentCensusData <- as.data.frame(matrix(NA, nrow=length(TotArea2010$Name), ncol=length(finalCensusCols)))
names(SegmentCensusData) <- finalCensusCols

##the 2010 data doesn't seem to have NAs
#one "-" for income in 2020 census data

#get the weighted average
for (s in 1:length(TotArea2010$Name)){
  
  seg <- TotArea2010$Name[s]
  
  sdata2010 <- CensusTracts2010[CensusTracts2010$Name == seg, ]
  sdata2020 <- CensusTracts2020[CensusTracts2020$Name_1 == seg, ]
  SegmentCensusData$Segment[s] <- seg
  
  # 2011
  SegmentCensusData[s, c("PercHispanicLatine11", "PercBlack11", "PercWhiteNonHL11", 
                         "MedHouseInc11", "PercRent11",  "PercRMov11")] <- sapply(sdata2010[,c("PercHispLat", "PercBlack", "PercWhiteNonHisp", "MedHouseIncome", "PercRenter","PercMovL5Years")], weAvg, weights=sdata2010$PercentArea)
    
  
  ###########Check for NAs
  if (length(na.omit(sdata2020$MedHouseIncome)) < length(sdata2020$MedHouseIncome)){
    
    ###the only NA so far is in income
    incdata <- na.omit(sdata2020$MedHouseIncome)
    adjustdata <- sdata2020$PercentArea[!is.na(sdata2020$MedHouseIncome)]/sum(sdata2020$PercentArea[!is.na(sdata2020$MedHouseIncome)])
    
    SegmentCensusData$MedHouseInc21[s] <- sum(incdata * adjustdata)
    
    SegmentCensusData[s, c("PercHispanicLatine21", "PercBlack21", "PercWhiteNonHL21", 
                         "PercRent21",  "PercRMov21", "SVI")] <- sapply(sdata2020[,c("PercHispLat", "PercBlack", "PercWhiteNonHisp", "PercRenter","PercMovL5Years", "SVI")], weAvg, weights=sdata2020$PercentArea)
    
    
  } else { #########no NAs
    #2021
  SegmentCensusData[s, c("PercHispanicLatine21", "PercBlack21", "PercWhiteNonHL21", 
                         "MedHouseInc21", "PercRent21",  "PercRMov21", "SVI")] <- sapply(sdata2020[,c("PercHispLat", "PercBlack", "PercWhiteNonHisp", "MedHouseIncome", "PercRenter","PercMovL5Years", "SVI")], weAvg, weights=sdata2020$PercentArea)
    
  }
}

#add a few last columns
SegmentCensusData$Change_PHL <- SegmentCensusData$PercHispanicLatine21 - SegmentCensusData$PercHispanicLatine11
SegmentCensusData$Change_PBl <- SegmentCensusData$PercBlack21 - SegmentCensusData$PercBlack11
SegmentCensusData$Change_PWnHL <- SegmentCensusData$PercWhiteNonHL21 - SegmentCensusData$PercWhiteNonHL11
SegmentCensusData$Change_MedHHI <- SegmentCensusData$MedHouseInc21 - SegmentCensusData$MedHouseInc11
SegmentCensusData$Avg_PRent <- (SegmentCensusData$PercRent21 + SegmentCensusData$PercRent11)/2
SegmentCensusData$Avg_Rmov <- (SegmentCensusData$PercRMov21 + SegmentCensusData$PercRMov11)/2

```


##Get Building and Zoning Averages
```{r building and zoning averages}

##########################################Building data
num_noNA <- table(BuildingParcels[!is.na(BuildingParcels$OBJECTID_1), c("Name")])

#permitting information
BuildingPermits$Year_issued <- format(as.Date(BuildingPermits$PermitIssueDate, "%m/%d/%Y"), "%Y")
perm_typs <- table(BuildingPermits[,c("Segment", "PermitType")])
perm_yrs_Reno <- table(BuildingPermits[BuildingPermits$PermitType == "Reno_Alt_add", c("Segment", "Year_issued")])
perm_yrs_NewCons <- table(BuildingPermits[BuildingPermits$PermitType == "NewConst", c("Segment", "Year_issued")])
perm_yrs_demo  <- table(BuildingPermits[BuildingPermits$PermitType == "Demo", c("Segment", "Year_issued")])

##start combining
BuiComb_nms <- c("Segment", "NumBuild", "NumConst_since11", "NumConst_since15", "NumDemo_since11", "NumDemo_since15", "NumReno_since11", "NumReno_since15")
Seg_building <- as.data.frame(matrix(0, nrow=24, ncol=length(BuiComb_nms)))
names(Seg_building) <- BuiComb_nms

Seg_building$Segment <- unique(BuildingParcels$Name)
Seg_building$NumBuild <- num_noNA

Seg_building$NumConst_since11[match(rownames(perm_yrs_NewCons), Seg_building$Segment)] <- rowSums(perm_yrs_NewCons[,c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")])
Seg_building$NumConst_since15[match(rownames(perm_yrs_NewCons), Seg_building$Segment)] <- rowSums(perm_yrs_NewCons[,c("2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")])

Seg_building$NumDemo_since11[match(rownames(perm_yrs_demo), Seg_building$Segment)]  <- rowSums(perm_yrs_demo[,c("2011", "2012", "2013", "2014", "2015", "2017", "2018", "2020", "2021", "2022", "2023")])
Seg_building$NumDemo_since15[match(rownames(perm_yrs_demo), Seg_building$Segment)]  <- rowSums(perm_yrs_demo[,c("2015", "2017", "2018", "2020", "2021", "2022", "2023")])


Seg_building$NumReno_since11[match(rownames(perm_yrs_Reno), Seg_building$Segment)] <- rowSums(perm_yrs_Reno[,c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")])
Seg_building$NumReno_since15[match(rownames(perm_yrs_Reno), Seg_building$Segment)] <- rowSums(perm_yrs_Reno[,c("2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023")])


##############################################################Zoning Data
TotArea <- ZoningDat %>% 
  group_by(Name) %>%
  summarize_at(vars("Area_m2"), sum, na.rm=TRUE)

zoning_cols <- c("Segment", "PercRes_z", "PercComm_z", "PercInst_z")
Zoning_bySeg <- as.data.frame(matrix(0, nrow=24, ncol=length(zoning_cols)))
names(Zoning_bySeg) <- zoning_cols

AreaBySimpleZone <- ZoningDat %>% 
  group_by(Name, SimplifiedZone) %>%
  summarize_at(vars("Area_m2"), sum, na.rm=TRUE)

AreaBySimpleZone <- AreaBySimpleZone[!is.na(AreaBySimpleZone$SimplifiedZone),]

Zoning_bySeg$Segment <- TotArea$Name
r1_inds <- match(AreaBySimpleZone$Name[AreaBySimpleZone$SimplifiedZone == "Residential"], TotArea$Name)
Zoning_bySeg$PercRes_z[r1_inds] <- AreaBySimpleZone$Area_m2[AreaBySimpleZone$SimplifiedZone == "Residential"]/TotArea$Area_m2[r1_inds]

r2_inds <- match(AreaBySimpleZone$Name[AreaBySimpleZone$SimplifiedZone == "Commercial"], TotArea$Name)
Zoning_bySeg$PercComm_z[r2_inds] <- AreaBySimpleZone$Area_m2[AreaBySimpleZone$SimplifiedZone == "Commercial"]/TotArea$Area_m2[r2_inds]

r3_inds <- match(AreaBySimpleZone$Name[AreaBySimpleZone$SimplifiedZone == "Institutional"], TotArea$Name)
Zoning_bySeg$PercInst_z[r3_inds] <- AreaBySimpleZone$Area_m2[AreaBySimpleZone$SimplifiedZone == "Institutional"]/TotArea$Area_m2[r3_inds]

```


##Multiple Tree Health Variables

Need to add some variables that are otherwise not in here (namely species-level variables).

```{r pull in species-lvl data}

#for ease later
TreeLvlCombined$GenSpe <- paste(TreeLvlCombined$Genus, TreeLvlCombined$Species, sep="_")

#To line up with species info
TreeLvlCombined$Species[TreeLvlCombined$Species == "unknown"| TreeLvlCombined$Species == "spp"] <- "spp."
TreeLvlCombined$DroughtTol <- rep(NA, length(TreeLvlCombined$TreeName))
TreeLvlCombined$SaltTol <- rep(NA, length(TreeLvlCombined$TreeName))
TreeLvlCombined$UrbanApp <- rep(NA, length(TreeLvlCombined$TreeName))

names(TreeLvlCombined)[names(TreeLvlCombined) == "CrownVigor"] <- "CrownStress"

##for a few weird species
TreeLvlCombined$Species[TreeLvlCombined$Species == "sylvatica"] <- "silvatica"
TreeLvlCombined$Species[TreeLvlCombined$Species == "x gradiflora"| TreeLvlCombined$Species == "grandiflora"| TreeLvlCombined$Species == "gradiflora" |TreeLvlCombined$Species == "grandifolia"] <- "x grandiflora"
TreeLvlCombined$Species[TreeLvlCombined$Species == "azerdarach"] <- "azedarach"
TreeLvlCombined$Species[TreeLvlCombined$Species == "indica "] <- "indica"
TreeLvlCombined$Species[TreeLvlCombined$Species == "buergeranum"|TreeLvlCombined$Species == "buergeranium"] <- "buergerianum"
TreeLvlCombined$Species[TreeLvlCombined$Species == "serrata" & TreeLvlCombined$Genus == "Prunus"] <- "serrulata"
TreeLvlCombined$Species[TreeLvlCombined$Species == "serotina"] <- "serrotina"

#row by row
for (t in 1:length(TreeLvlCombined$X)){
  YesGen <- SppSpecificData$Genus == TreeLvlCombined$Genus[t]
  YesSpp <- SppSpecificData$Species == TreeLvlCombined$Species[t]
  
  SppInfoInd <- c(1:length(SppSpecificData[,1]))[(YesGen & YesSpp)]
  
  #what do you do if you don't have info on this species
  if(length(SppInfoInd) == 0){
    print(paste("Error, no species information for", TreeLvlCombined$GenSpe[t], "Tree #", t))
    
    ##try to fill it in with the default for the genus
    Spp2 <- SppSpecificData$Species =="spp."
    SppInfoInd2 <- c(1:length(SppSpecificData[,1]))[(YesGen & Spp2)]
    
    if(length(SppInfoInd2) == 0){
      print(paste("Error, no generic genus-level information for", TreeLvlCombined$Genus[t], "Tree #", t))
      next #go to the next tree
    } else {
    TreeLvlCombined$DroughtTol[t] <- SppSpecificData$DroughtTol[SppInfoInd2]
    TreeLvlCombined$SaltTol[t] <- SppSpecificData$SaltTol[SppInfoInd2]
    TreeLvlCombined$UrbanApp[t] <- SppSpecificData$StreetUrban[SppInfoInd2]
    }
  
  #have a species-level match
  } else {
    TreeLvlCombined$DroughtTol[t] <- SppSpecificData$DroughtTol[SppInfoInd]
    TreeLvlCombined$SaltTol[t] <- SppSpecificData$SaltTol[SppInfoInd]
    TreeLvlCombined$UrbanApp[t] <- SppSpecificData$StreetUrban[SppInfoInd]
  } #seeing if there is a match
  
}

##Species group adjustment
TreeLvlCombined$GenSpe[TreeLvlCombined$GenSpe == "Lagerstroemia_unknown"| TreeLvlCombined$GenSpe == "Lagerstroemia_indica"] <- "Lagerstroemia_spp"
TreeLvlCombined$GenSpe[TreeLvlCombined$Genus == "Prunus"] <- "Prunus_spp"
SppFreq <- sort(table(TreeLvlCombined$GenSpe),decreasing = TRUE)
CommonSpp <- SppFreq[SppFreq > 50]

#Create a species group category
TreeLvlCombined$SppGroup <- rep("Other", length(TreeLvlCombined$TreeName))
TreeLvlCombined$SppGroup[TreeLvlCombined$GenSpe %in% names(CommonSpp)] <- TreeLvlCombined$GenSpe[TreeLvlCombined$GenSpe %in% names(CommonSpp)]

TreeLvlCombined$SppGroup <- as.factor(TreeLvlCombined$SppGroup) #for model
TreeLvlCombined$SppGroup <- relevel(TreeLvlCombined$SppGroup, ref = "Other")

##make a genus-lvl grouping 
TreeLvlCombined$GenusGroup <- TreeLvlCombined$Genus
GenusFreq <- table(TreeLvlCombined$Genus)
GenusFreq <- GenusFreq[GenusFreq > 40]

TreeLvlCombined$GenusGroup[!(TreeLvlCombined$GenusGroup %in% names(GenusFreq))] <- "Other"
TreeLvlCombined$GenusGroup <- as.factor(TreeLvlCombined$GenusGroup )
TreeLvlCombined$GenusGroup <- relevel(TreeLvlCombined$GenusGroup, ref = "Other")

```



```{r prep response data}
#to make it easier to correct mistakes + focus on street trees
TreeLvlCombined_mod <- TreeLvlCombined[TreeLvlCombined$Segment != "Duke" & TreeLvlCombined$Segment != "Park",]

#Get rid of trees without local site conditions
TreeLvlCombined_mod <- TreeLvlCombined_mod[!is.na(TreeLvlCombined_mod$Gardenscape),]

#calculate basal area
TreeLvlCombined_mod$BasalArea <- sapply(TreeLvlCombined_mod$DBHTot, basalArea)
TreeLvlCombined_mod <- TreeLvlCombined_mod[TreeLvlCombined_mod$BasalArea > 0, ] #because we need some kind of BA

#get segment as a factor
TreeLvlCombined_mod$Segment <- as.factor(TreeLvlCombined_mod$Segment)

#Year
TreeLvlCombined_mod$Year <- as.factor(TreeLvlCombined_mod$Year)


###########################################Cues to care

###########create Mulch categories
TreeLvlCombined_mod$Mulch[TreeLvlCombined_mod$Mulch == 1] <- "Mulch"
TreeLvlCombined_mod$Mulch[TreeLvlCombined_mod$Mulch == FALSE] <- "None"
TreeLvlCombined_mod$Mulch[TreeLvlCombined_mod$MulchVolcano == 1] <- "Volcano"

TreeLvlCombined_mod$Mulch <- as.factor(TreeLvlCombined_mod$Mulch)
TreeLvlCombined_mod$Mulch <- relevel(TreeLvlCombined_mod$Mulch, ref = "None")

##put a correctly mulched metric in place
TreeLvlCombined_mod$CorrMulch <- TreeLvlCombined_mod$Mulch
TreeLvlCombined_mod$CorrMulch <- as.character(TreeLvlCombined_mod$CorrMulch)
TreeLvlCombined_mod$CorrMulch[TreeLvlCombined_mod$CorrMulch == "Mulch"] <- 1
TreeLvlCombined_mod$CorrMulch[TreeLvlCombined_mod$CorrMulch != 1] <- 0

########Translate Gardenscape
TreeLvlCombined_mod$Gardenscape[TreeLvlCombined_mod$Gardenscape==""] <- "None"
h1 <- c("None", "Minimal", "Moderate", "Extensive")
h2 <- c(1:4)
GDict <- as.data.frame(matrix(c(h1,h2), nrow=4, ncol=2, byrow=FALSE))
names(GDict) <- c("Original", "Simplified")

TreeLvlCombined_mod$Gardenscape <- GDict$Simplified[match(TreeLvlCombined_mod$Gardenscape, GDict$Original)]

TreeLvlCombined_mod$Gardenscape <- as.character(TreeLvlCombined_mod$Gardenscape)
TreeLvlCombined_mod$Gardenscape[TreeLvlCombined_mod$Gardenscape == 3] <- 4
TreeLvlCombined_mod$Gardenscape[TreeLvlCombined_mod$Gardenscape == 2] <- 3
TreeLvlCombined_mod$Gardenscape[TreeLvlCombined_mod$Gardenscape == 1] <- 2
TreeLvlCombined_mod$Gardenscape[TreeLvlCombined_mod$Gardenscape == 2 & TreeLvlCombined_mod$Mowing %in% c("old", "potentially never")] <- 1
TreeLvlCombined_mod$Gardenscape <- as.factor(TreeLvlCombined_mod$Gardenscape)

#######Pruning
TreeLvlCombined_mod$PrunedCorrect <-TreeLvlCombined_mod$Pruned
TreeLvlCombined_mod$PrunedCorrect[TreeLvlCombined_mod$HatrackPrune == 1 | TreeLvlCombined_mod$FlushCutPrune == 1] <- 0



#######################################################################Site conditions
##Group Land Use categories
TreeLvlCombined_mod$LandUse <- as.character(TreeLvlCombined_mod$LandUse)
TreeLvlCombined_mod$LandUse[TreeLvlCombined_mod$LandUse == "SFR-A" | TreeLvlCombined_mod$LandUse == "SFR-D" | TreeLvlCombined_mod$LandUse == "MFR"] <- "Res"
TreeLvlCombined_mod$LandUse[TreeLvlCombined_mod$LandUse == "COMM" | TreeLvlCombined_mod$LandUse == "MIX"] <- "COMM_Mx"
TreeLvlCombined_mod$LandUse[is.null(TreeLvlCombined_mod$LandUse) |TreeLvlCombined_mod$LandUse == "V" | TreeLvlCombined_mod$LandUse == "IND" | TreeLvlCombined_mod$LandUse == "UT" | TreeLvlCombined_mod$LandUse == "TR" | TreeLvlCombined_mod$LandUse == "AG" | TreeLvlCombined_mod$LandUse == ""| TreeLvlCombined_mod$LandUse == "MP" | TreeLvlCombined_mod$LandUse == "NAT"] <- "Other"
TreeLvlCombined_mod$LandUse <- as.factor(TreeLvlCombined_mod$LandUse)
TreeLvlCombined_mod$LandUse <- relevel(TreeLvlCombined_mod$LandUse, ref="Res")


##SiteType
#Site type
TreeLvlCombined_mod$SiteType <- as.character(TreeLvlCombined_mod$SiteType)
TreeLvlCombined_mod$SiteType[TreeLvlCombined_mod$SiteType == "FY" | TreeLvlCombined_mod$SiteType == "SY"] <- "Yard"
TreeLvlCombined_mod$SiteType[TreeLvlCombined_mod$SiteType == "OM" | TreeLvlCombined_mod$SiteType == "OH"| TreeLvlCombined_mod$SiteType == "PB"] <- "OMH"
TreeLvlCombined_mod$SiteType[is.null(TreeLvlCombined_mod$SiteType) |TreeLvlCombined_mod$SiteType== ""| TreeLvlCombined_mod$SiteType== "NAT"] <- "Other"
TreeLvlCombined_mod$SiteType <- as.factor(TreeLvlCombined_mod$SiteType)
TreeLvlCombined_mod$SiteType <- relevel(TreeLvlCombined_mod$SiteType, ref="SC")


#Crown Light
TreeLvlCombined_mod$CrownLight <- as.numeric(TreeLvlCombined_mod$CrownLight)
TreeLvlCombined_mod$CrownLight <- round(TreeLvlCombined_mod$CrownLight)
TreeLvlCombined_mod$CrownLight[TreeLvlCombined_mod$CrownLight == 0] <- 1
TreeLvlCombined_mod$CrownLight[is.na(TreeLvlCombined_mod$CrownLight)] <- 3 #just give it a moderate value
TreeLvlCombined_mod$CrownLight <- as.factor(TreeLvlCombined_mod$CrownLight)


##Need to modify the Percent Imperv because some of the categories are very low
names(TreeLvlCombined_mod)[names(TreeLvlCombined_mod) == "PercImperv"] <- "PercentImperv"
TreeLvlCombined_mod$PercentImperv <- as.numeric(TreeLvlCombined_mod$PercentImperv)
TreeLvlCombined_mod$PercentImperv[TreeLvlCombined_mod$PercentImperv <=2] <- 1 #less than 26% imperv
TreeLvlCombined_mod$PercentImperv[TreeLvlCombined_mod$PercentImperv ==3] <- 2 #26-50
TreeLvlCombined_mod$PercentImperv[TreeLvlCombined_mod$PercentImperv ==4] <- 3 #51-75
TreeLvlCombined_mod$PercentImperv[TreeLvlCombined_mod$PercentImperv ==5] <- 4 #76-100
TreeLvlCombined_mod$PercentImperv <- as.factor(TreeLvlCombined_mod$PercentImperv)

##############################Tree Health
#collapsing the categories here for ease
TreeLvlCombined_mod$Dieback[((TreeLvlCombined_mod$Dieback > 3) & (TreeLvlCombined_mod$Dieback <= 6))] <- 4 #11-25%
TreeLvlCombined_mod$Dieback[(TreeLvlCombined_mod$Dieback > 6)] <- 5 #25%+
TreeLvlCombined_mod$Dieback[TreeLvlCombined_mod$CrownStress >= 5] <- 5 #trees are dead

##because there are not enough categories
TreeLvlCombined_mod$Defoliation[TreeLvlCombined_mod$Defoliation > 3] <- 3
TreeLvlCombined_mod$Discoloration[TreeLvlCombined_mod$Discoloration > 4] <- 4

#Get rid of 0.5
TreeLvlCombined_mod$Discoloration <- round(TreeLvlCombined_mod$Discoloration)
TreeLvlCombined_mod$Defoliation <- round(TreeLvlCombined_mod$Defoliation)
TreeLvlCombined_mod$Dieback <- round(TreeLvlCombined_mod$Dieback)


```


###Look at segment-level response

```{r pull in tree data}

##first need to get just one entry per tree
colsSto <- names(TreeLvlCombined_mod)
uniTrees <- unique(TreeLvlCombined_mod$TreeName)
UniqueTreeData <- as.data.frame(matrix(0, ncol=length(colsSto), nrow = length(uniTrees)))
names(UniqueTreeData) <- colsSto

TreeData_SegLvl <- TreeLvlCombined_mod

TreeData_SegLvl$Year <- as.numeric(as.character(TreeData_SegLvl$Year))
TreeData_SegLvl$LandUse <- as.character(TreeData_SegLvl$LandUse)
TreeData_SegLvl$SiteType <- as.character(TreeData_SegLvl$SiteType)

MatInd <- 1

#get one row per tree
for (u in 1:length(uniTrees)){
  
  treeName <- uniTrees[u]
  treedata <- TreeData_SegLvl[na.omit(TreeData_SegLvl$TreeName == treeName),]
  treedata <- treedata[!is.na(treedata$TreeName),]
  
  mostRecYr <- max(na.omit(as.numeric(treedata$Year)))
  
  Dat2Use <- treedata[treedata$Year == mostRecYr, ]
  
  UniqueTreeData[MatInd,] <- Dat2Use[1,]
  
  MatInd <- MatInd + 1
  
}

#UniqueTreeData <- UniqueTreeData[, c(3:10, 13:37,41, 45:51)]
UniqueTreeData <- UniqueTreeData[!is.na(UniqueTreeData$TreeName),]

#for diversity, I think you the number of trees of a given species for each segment
UniqueTreeData$Segment <- levels(TreeData_SegLvl$Segment)[as.numeric(UniqueTreeData$Segment)]

SppSeg <- table(UniqueTreeData[, c("Segment", "GenSpe")])
simpsonDivSegs <- diversity(SppSeg, index="simpson")

GenSeg <- table(UniqueTreeData[, c("Segment", "Genus")])
simpsonDivSegs_gen <- diversity(GenSeg, index="simpson")

##need things to be numeric in order for it to work
UniqueTreeData$CorrMulch <- as.numeric(UniqueTreeData$CorrMulch)

SegAvg_UniqueDat <- UniqueTreeData %>%
  group_by(Segment) %>%
  summarize_at(vars("BasalArea", "CorrMulch", "PrunedCorrect", "UrbanApp"), mean, na.rm=TRUE)

TotalSegTrees <- table(UniqueTreeData$Segment)

#Site Type
Seg_SiteType_Counts <- table(UniqueTreeData[,c("Segment", "SiteType")])
Perc_SegST <- sweep(Seg_SiteType_Counts, 1, TotalSegTrees, FUN='/')
#from this, probably most useful to look at percent SC or SP and then Percent FY or SY
#with mod, use SP, SC, Yard

#Land Use
Seg_LandUse_Counts <- table(UniqueTreeData[,c("Segment", "LandUse")])
Perc_SegLU <- sweep(Seg_LandUse_Counts, 1, TotalSegTrees, FUN='/')
#here, look at SFR-A and SFR-D versus MFR vs COMM vs INST vs Other?
#Res, MP_INST

#Percent Impervious
Seg_PI_Counts <- table(UniqueTreeData[,c("Segment", "PercentImperv")])
Perc_SegPI <- sweep(Seg_PI_Counts, 1, TotalSegTrees, FUN='/')
#kind of like your analyses, maybe combine 1 and 2, then 3, then 4 and 5 combined

#Gardenscape
Seg_Gardenscape_Counts <- table(UniqueTreeData[,c("Segment", "Gardenscape")])
Perc_SegGard <- sweep(Seg_Gardenscape_Counts, 1, TotalSegTrees, FUN='/')
#use whatever you used in the analyses above
#do 1, 2, 3+?, or maybe do 1 and 4/5 and leave the rest to be moderate?

#Tree Health
#should use the same groupings as I did for the analyses above
#for these it is probably worth pulling in all the cateories to start with and adjust as needed
#maybe ignore defoliation because you only have 2 categories?
Seg_Discol_Counts <- table(UniqueTreeData[,c("Segment", "Discoloration")])
Perc_SegDisc <- sweep(Seg_Discol_Counts, 1, TotalSegTrees, FUN='/')
Seg_Defol_Counts <- table(UniqueTreeData[,c("Segment", "Defoliation")])
Perc_SegDef <- sweep(Seg_Defol_Counts, 1, TotalSegTrees, FUN='/')
Seg_DBK_Counts <- table(UniqueTreeData[,c("Segment", "Dieback")])
Perc_SegDBK <- sweep(Seg_DBK_Counts, 1, TotalSegTrees, FUN='/')
Seg_CS_Counts <- table(UniqueTreeData[,c("Segment", "CrownStress")])
Perc_SegCS <- sweep(Seg_CS_Counts, 1, TotalSegTrees, FUN='/')


##Get the total number of trees
totNumTreesSegment <- table(UniqueTreeData[,c("Segment")])

```



```{r combine data}
##################################################Combine all the data
nrows <- length(SegAvg_UniqueDat$Segment)
SegDatCols <- c("Segment", "AvgBA", "PercCorrMulch", "PercUrbanApp", "PercResTree", "PercCOMM_MxTree", "PercSC", "PercGar3o4", "PercDisc3o4", "PercDBK5", "PercCS4o5", "SimpsonsDivSpp", "SimpsonsDivGen", "totNumTrees")
SegmentLvlDat <- as.data.frame(matrix(NA, nrow=nrows, ncol=length(SegDatCols)))
names(SegmentLvlDat) <- SegDatCols

SegNms <- na.omit(unique(SegAvg_UniqueDat$Segment))


##Add census data to empty df
for(s in 1:length(SegNms)){
  
  seg <- SegNms[s]
  SegmentLvlDat$Segment[s] <- seg
  
  ####Pull in the non-census data
  SegInd_treed <- match(seg, SegAvg_UniqueDat$Segment)
  
  SegmentLvlDat$AvgBA[s] <- SegAvg_UniqueDat$BasalArea[SegInd_treed]
  SegmentLvlDat$PercCorrMulch[s] <- SegAvg_UniqueDat$CorrMulch[SegInd_treed]
  #SegmentLvlDat$PercPrunedCorrect[s] <- SegAvg_UniqueDat$PrunedCorrect[SegInd_treed]
  SegmentLvlDat$PercUrbanApp[s] <- SegAvg_UniqueDat$UrbanApp[SegInd_treed]
  
  ##have to pull from other summaries
  segInd_Sum <- match(seg, rownames(Perc_SegLU))
  
  SegmentLvlDat$PercResTree[s] <- Perc_SegLU[segInd_Sum, match("Res", colnames(Perc_SegLU))]
  SegmentLvlDat$PercCOMM_MxTree[s] <- Perc_SegLU[segInd_Sum, match("COMM_Mx", colnames(Perc_SegLU))]
  SegmentLvlDat$PercSC[s] <- Perc_SegST[segInd_Sum, match("SC", colnames(Perc_SegST))]
  SegmentLvlDat$PercGar3o4[s] <- Perc_SegGard[segInd_Sum,match("3", colnames(Perc_SegGard))] + Perc_SegGard[SegInd_treed,match("4", colnames(Perc_SegGard))]
  
  #tree health outcomes
  SegmentLvlDat$PercDisc3o4[s] <- Perc_SegDisc[segInd_Sum, match("3", colnames(Perc_SegDisc))] + Perc_SegDisc[SegInd_treed, match("4", colnames(Perc_SegDisc))]
  SegmentLvlDat$PercDBK5[s] <- Perc_SegDBK[segInd_Sum, match("5", colnames(Perc_SegDBK))]
  SegmentLvlDat$PercCS4o5[s] <- Perc_SegCS[segInd_Sum, match("4", colnames(Perc_SegCS))] + Perc_SegCS[SegInd_treed, match("5", colnames(Perc_SegCS))]
  
  ##Diversity
  SegmentLvlDat$SimpsonsDivSpp[s] <- as.vector(simpsonDivSegs[match(seg, names(simpsonDivSegs))])
  SegmentLvlDat$SimpsonsDivGen[s] <- as.vector(simpsonDivSegs_gen[match(seg, names(simpsonDivSegs_gen))])
  
  #basic info
  SegmentLvlDat$totNumTrees[s] <- totNumTreesSegment[match(seg, names(totNumTreesSegment))]
  
}

SegmentLvlDat <- SegmentLvlDat[!is.na(SegmentLvlDat$Segment),]


```



##Turn into Segment-level data

```{r seg from sum}

#get relevant zoning data
Zoning_bySeg <- Zoning_bySeg[Zoning_bySeg$Segment %in% unique(SegmentLvlDat$Segment),]

#need to make sure the order is the same for all of these - and the buildings are not to start with


TreeZone <- merge(SegmentLvlDat, Zoning_bySeg, by="Segment")
TreeZCens <- merge(TreeZone, SegmentCensusData, by="Segment")
Seg_allData <- merge(TreeZCens, Seg_building, by="Segment")

AnalysisCols <- c("PercSC", "PercGar3o4", "SimpsonsDivSpp", "SimpsonsDivGen", "PercCorrMulch","AvgBA", "PercUrbanApp", "PercDBK5", "PercDisc3o4", "PercCS4o5")

#go through and slightly adjust the variables that will be modeled with a beta distribution
for(c in 1:length(AnalysisCols)){
  
  v <- AnalysisCols[c]
  v_ind <- match(v, names(Seg_allData))
  
  Seg_allData[(Seg_allData[,v_ind] == 0) ,v_ind] <- 0.0001
  Seg_allData[(Seg_allData[,v_ind] == 1) ,v_ind] <- 0.9999
  
}


write.csv(Seg_allData, "../01Data/Durham/DurhamSegmentData.csv")

```